name: Build and Deploy
on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled, closed, reopened]
  workflow_dispatch:

# Add permissions to allow GitHub Actions to push to the repo
permissions:
  contents: write
  pages: write
  id-token: write
  issues: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Fetch Issues
        run: npm run fetch-issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: renocrypt
          REPO_NAME: ds-de-blog

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist